### ISSUE TITLE
Test Comments

### ISSUE THREAD

**Issue by algokelvin-373** [pepriandika/PelatihanAndroid#1]
Yuk berkomentar

**Comment by algokelvin-373** [comment]
@pepriandika

**Comment by pepriandika** [comment]
balasanku

**Comment by algokelvin-373** [comment]
Good job @pepriandika

**Comment by algokelvin-373** [comment]
Try, try, and try again until you understand

**Comment by pepriandika** [comment]
> Try, try, and try again until you understand

Siap, terima kasih Pak.

**Comment by algokelvin-373** [comment]
> > Try, try, and try again until you understand
> 
> Siap, terima kasih Pak.

You're welcome

**Comment by algokelvin-373** [comment]
I close this issue.
If you want to ask something, you can create a new issue.
Thank you.

Regards,
AlgoKelvin
